//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace di.proyecto.clase.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tallerEntities : DbContext
    {
        public tallerEntities()
            : base("name=tallerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<albaran> albaran { get; set; }
        public virtual DbSet<averia> averia { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<detalles_ticket> detalles_ticket { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<pedidos> pedidos { get; set; }
        public virtual DbSet<permisos> permisos { get; set; }
        public virtual DbSet<piezas_averia> piezas_averia { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<proveedor> proveedor { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<ticket_venta> ticket_venta { get; set; }
        public virtual DbSet<tipoaveria> tipoaveria { get; set; }
        public virtual DbSet<tipoproducto> tipoproducto { get; set; }
        public virtual DbSet<vehiculo> vehiculo { get; set; }
    }
}
