//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace di.proyecto.clase.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class diinventarioEntities : DbContext
    {
        public diinventarioEntities()
            : base("name=diinventarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<articulo> articulo { get; set; }
        public virtual DbSet<departamento> departamento { get; set; }
        public virtual DbSet<espacio> espacio { get; set; }
        public virtual DbSet<ficheromodelo> ficheromodelo { get; set; }
        public virtual DbSet<ficherousuario> ficherousuario { get; set; }
        public virtual DbSet<grupo> grupo { get; set; }
        public virtual DbSet<modeloarticulo> modeloarticulo { get; set; }
        public virtual DbSet<permiso> permiso { get; set; }
        public virtual DbSet<permisosrol> permisosrol { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<salida> salida { get; set; }
        public virtual DbSet<tipoarticulo> tipoarticulo { get; set; }
        public virtual DbSet<tipousuario> tipousuario { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
