//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace di.proyecto.clase.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class piezas_averia
    {
        public int idAveria { get; set; }
        public int idProducto { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<float> IVA { get; set; }
        public Nullable<float> precioTotal { get; set; }
    
        public virtual averia averia { get; set; }
        public virtual productos productos { get; set; }
    }
}
